import type { Property } from "@/types";

export const listings: Property[] = [
  // ─── OAKLAND ──────────────────────────────────────────
  {
    id: "1",
    slug: "craftsman-charm-rockridge",
    address: "5432 College Ave",
    city: "Oakland",
    neighborhood: "Rockridge",
    neighborhoodSlug: "rockridge",
    price: 1495000,
    beds: 3,
    baths: 2,
    sqft: 1850,
    lotSqft: 4800,
    status: "active",
    propertyType: "house",
    description:
      "Stunning Craftsman bungalow on tree-lined College Ave. Original details lovingly preserved — built-in bookcases, box-beam ceilings, and a gorgeous stone fireplace. Updated kitchen with quartz counters opens to a sun-drenched back garden. Two blocks from Rockridge BART.",
    features: ["Craftsman details", "Updated kitchen", "Garden", "Near BART", "Hardwood floors"],
    yearBuilt: 1922,
    daysOnMarket: 12,
    pricePerSqft: 808,
    garage: 1,
    stories: 2,
    mlsNumber: "EB-40291834",
    listDate: "2026-02-19",
    images: [],
  },
  {
    id: "2",
    slug: "modern-loft-jack-london",
    address: "311 Oak St #405",
    city: "Oakland",
    neighborhood: "Jack London Square",
    neighborhoodSlug: "jack-london-square",
    price: 685000,
    beds: 1,
    baths: 1,
    sqft: 920,
    status: "active",
    propertyType: "condo",
    description:
      "Sleek, sun-filled loft in the heart of Jack London Square. 14-foot ceilings, floor-to-ceiling windows with Bay Bridge views, and an open chef's kitchen. Building amenities include rooftop deck, gym, and secure parking. Walk to ferry, restaurants, and waterfront.",
    features: ["Bay views", "14ft ceilings", "Rooftop deck", "Gym", "Secure parking"],
    yearBuilt: 2019,
    daysOnMarket: 22,
    pricePerSqft: 745,
    hoa: 485,
    mlsNumber: "EB-40291567",
    listDate: "2026-02-09",
    images: [],
  },
  {
    id: "3",
    slug: "hillside-retreat-montclair",
    address: "1789 Skyline Blvd",
    city: "Oakland",
    neighborhood: "Montclair",
    neighborhoodSlug: "montclair",
    price: 1875000,
    beds: 4,
    baths: 3,
    sqft: 2650,
    lotSqft: 8200,
    status: "active",
    propertyType: "house",
    description:
      "Perched in the Oakland Hills with jaw-dropping panoramic Bay views. This mid-century modern gem features walls of glass, a spacious deck overlooking the Bay, and direct trail access to Joaquin Miller Park. Montclair Village shops and dining just minutes away.",
    features: ["Panoramic Bay views", "Mid-century modern", "Trail access", "Large deck", "2-car garage"],
    yearBuilt: 1958,
    daysOnMarket: 8,
    pricePerSqft: 708,
    garage: 2,
    stories: 2,
    mlsNumber: "EB-40292103",
    listDate: "2026-02-23",
    images: [],
  },
  {
    id: "4",
    slug: "lakeside-gem-lake-merritt",
    address: "246 Lakeshore Ave #302",
    city: "Oakland",
    neighborhood: "Lake Merritt",
    neighborhoodSlug: "lake-merritt",
    price: 625000,
    beds: 2,
    baths: 1,
    sqft: 1100,
    status: "active",
    propertyType: "condo",
    description:
      "Charming art deco condo overlooking Lake Merritt. Wake up to lake views, walk to the Saturday farmers market, and enjoy the 3.4-mile lakeside path at your doorstep. Updated bath, in-unit laundry, and deeded parking.",
    features: ["Lake views", "Art deco", "In-unit laundry", "Deeded parking", "Near BART"],
    yearBuilt: 1936,
    daysOnMarket: 15,
    pricePerSqft: 568,
    hoa: 375,
    mlsNumber: "EB-40291402",
    listDate: "2026-02-16",
    images: [],
  },
  {
    id: "5",
    slug: "creative-live-work-temescal",
    address: "4721 Telegraph Ave",
    city: "Oakland",
    neighborhood: "Temescal",
    neighborhoodSlug: "temescal",
    price: 899000,
    beds: 2,
    baths: 2,
    sqft: 1350,
    lotSqft: 2200,
    status: "active",
    propertyType: "townhouse",
    description:
      "Live-work townhouse on vibrant Telegraph Ave. Ground floor studio/office space, two bedrooms upstairs, private rooftop deck with Oakland Hills views. Steps to Temescal's best restaurants, shops, and the MacArthur BART station.",
    features: ["Live-work space", "Rooftop deck", "Hills views", "Near BART", "Modern finishes"],
    yearBuilt: 2015,
    daysOnMarket: 18,
    pricePerSqft: 666,
    stories: 3,
    mlsNumber: "EB-40291290",
    listDate: "2026-02-13",
    images: [],
  },
  {
    id: "6",
    slug: "grand-victorian-piedmont-ave",
    address: "108 Piedmont Ave",
    city: "Oakland",
    neighborhood: "Piedmont Avenue",
    neighborhoodSlug: "piedmont-ave",
    price: 1325000,
    beds: 3,
    baths: 2.5,
    sqft: 2100,
    lotSqft: 5200,
    status: "pending",
    propertyType: "house",
    description:
      "Grand Victorian on prestigious Piedmont Avenue with classic period details — ornate moldings, stained glass, and a wraparound porch. Thoughtfully updated with modern kitchen and baths while preserving original character. Walk to shops and restaurants.",
    features: ["Victorian charm", "Wraparound porch", "Stained glass", "Updated kitchen", "Walkable"],
    yearBuilt: 1895,
    daysOnMarket: 6,
    pricePerSqft: 631,
    garage: 1,
    stories: 2,
    mlsNumber: "EB-40292287",
    listDate: "2026-02-25",
    images: [],
  },
  {
    id: "7",
    slug: "sunny-bungalow-dimond",
    address: "2156 Fruitvale Ave",
    city: "Oakland",
    neighborhood: "Dimond",
    neighborhoodSlug: "dimond",
    price: 875000,
    beds: 3,
    baths: 1.5,
    sqft: 1450,
    lotSqft: 5000,
    status: "active",
    propertyType: "house",
    description:
      "Sun-drenched bungalow in the heart of the Dimond district. Bright open floor plan, refinished hardwood floors, and a landscaped backyard with mature fruit trees. Walking distance to La Farine Bakery, Dimond Park, and canyon trails.",
    features: ["Fruit trees", "Hardwood floors", "Open floor plan", "Near trails", "Quiet street"],
    yearBuilt: 1940,
    daysOnMarket: 10,
    pricePerSqft: 603,
    garage: 1,
    stories: 1,
    mlsNumber: "EB-40292044",
    listDate: "2026-02-21",
    images: [],
  },
  {
    id: "8",
    slug: "waterfront-condo-adams-point",
    address: "1800 Lakeshore Dr #601",
    city: "Oakland",
    neighborhood: "Adams Point",
    neighborhoodSlug: "adams-point",
    price: 545000,
    beds: 1,
    baths: 1,
    sqft: 780,
    status: "active",
    propertyType: "condo",
    description:
      "Top-floor Adams Point condo with sweeping Lake Merritt views. Open floor plan, updated kitchen, floor-to-ceiling windows. Walk to Grand Avenue dining, 19th Street BART, and the lakeside path. Perfect starter home or investment.",
    features: ["Lake views", "Top floor", "Updated kitchen", "Walk to BART", "Doorman building"],
    yearBuilt: 1965,
    daysOnMarket: 25,
    pricePerSqft: 699,
    hoa: 420,
    mlsNumber: "EB-40291088",
    listDate: "2026-02-06",
    images: [],
  },

  // ─── BERKELEY ─────────────────────────────────────────
  {
    id: "11",
    slug: "north-berkeley-craftsman",
    address: "1423 Hopkins St",
    city: "Berkeley",
    neighborhood: "North Berkeley",
    neighborhoodSlug: "north-berkeley",
    price: 1650000,
    beds: 4,
    baths: 2.5,
    sqft: 2200,
    lotSqft: 5800,
    status: "active",
    propertyType: "house",
    description:
      "Exquisite brown-shingle Craftsman on a quiet North Berkeley street. Four spacious bedrooms, a chef's kitchen with Viking appliances, and a sprawling backyard with mature lemon trees. Walk to the Gourmet Ghetto, Chez Panisse, and North Berkeley BART.",
    features: ["Brown shingle", "Chef's kitchen", "Lemon trees", "Walk to Gourmet Ghetto", "Near BART"],
    yearBuilt: 1912,
    daysOnMarket: 5,
    pricePerSqft: 750,
    garage: 1,
    stories: 2,
    mlsNumber: "EB-40292401",
    listDate: "2026-02-26",
    images: [],
  },
  {
    id: "12",
    slug: "elmwood-tudor",
    address: "2845 Ashby Ave",
    city: "Berkeley",
    neighborhood: "Elmwood",
    neighborhoodSlug: "elmwood",
    price: 1425000,
    beds: 3,
    baths: 2,
    sqft: 1900,
    lotSqft: 4600,
    status: "active",
    propertyType: "house",
    description:
      "Storybook Tudor in the coveted Elmwood neighborhood. Arched doorways, leaded glass windows, and a cozy brick fireplace. Beautifully landscaped garden with a detached cottage perfect for a home office or ADU conversion. Near UC Berkeley campus.",
    features: ["Tudor style", "Leaded glass", "ADU potential", "Garden cottage", "Near UC Berkeley"],
    yearBuilt: 1928,
    daysOnMarket: 9,
    pricePerSqft: 750,
    garage: 1,
    stories: 2,
    mlsNumber: "EB-40292310",
    listDate: "2026-02-22",
    images: [],
  },
  {
    id: "13",
    slug: "downtown-berkeley-condo",
    address: "2120 Shattuck Ave #804",
    city: "Berkeley",
    neighborhood: "Downtown Berkeley",
    neighborhoodSlug: "downtown-berkeley",
    price: 725000,
    beds: 2,
    baths: 2,
    sqft: 1050,
    status: "active",
    propertyType: "condo",
    description:
      "Bright corner unit in downtown Berkeley's premier high-rise. Floor-to-ceiling windows, modern finishes, quartz counters, and a private balcony with Golden Gate views. Steps to Downtown Berkeley BART, restaurants, and the UC campus.",
    features: ["Golden Gate views", "Corner unit", "Balcony", "Modern finishes", "Walk to BART"],
    yearBuilt: 2021,
    daysOnMarket: 14,
    pricePerSqft: 690,
    hoa: 550,
    mlsNumber: "EB-40291955",
    listDate: "2026-02-17",
    images: [],
  },
  {
    id: "14",
    slug: "berkeley-hills-panoramic",
    address: "950 Grizzly Peak Blvd",
    city: "Berkeley",
    neighborhood: "Berkeley Hills",
    neighborhoodSlug: "berkeley-hills",
    price: 2350000,
    beds: 5,
    baths: 3.5,
    sqft: 3400,
    lotSqft: 12000,
    status: "active",
    propertyType: "house",
    description:
      "Stunning contemporary perched in the Berkeley Hills with unobstructed Golden Gate and Bay views. Walls of glass, open floor plan, chef's kitchen with waterfall island, and a resort-style backyard with pool and outdoor kitchen. Ultimate indoor-outdoor living.",
    features: ["Golden Gate views", "Pool", "Outdoor kitchen", "Smart home", "EV charger"],
    yearBuilt: 2018,
    daysOnMarket: 16,
    pricePerSqft: 691,
    garage: 2,
    stories: 3,
    mlsNumber: "EB-40291788",
    listDate: "2026-02-15",
    images: [],
  },
  {
    id: "15",
    slug: "claremont-classic",
    address: "55 Claremont Blvd",
    city: "Berkeley",
    neighborhood: "Claremont",
    neighborhoodSlug: "claremont",
    price: 1950000,
    beds: 4,
    baths: 3,
    sqft: 2800,
    lotSqft: 7200,
    status: "pending",
    propertyType: "house",
    description:
      "Elegant Mediterranean in the prestigious Claremont neighborhood. Barrel tile roof, arched windows, and a courtyard entry. Renovated with designer finishes — marble baths, custom cabinetry, and Wolf/Sub-Zero appliances. Near the Claremont Hotel and Rockridge shops.",
    features: ["Mediterranean style", "Designer finishes", "Courtyard", "Wolf/Sub-Zero", "Near Claremont Hotel"],
    yearBuilt: 1935,
    daysOnMarket: 4,
    pricePerSqft: 696,
    garage: 2,
    stories: 2,
    mlsNumber: "EB-40292455",
    listDate: "2026-02-27",
    images: [],
  },

  // ─── BROADER EAST BAY ─────────────────────────────────
  {
    id: "16",
    slug: "alameda-victorian-charm",
    address: "1534 Park St",
    city: "Alameda",
    neighborhood: "Park Street",
    neighborhoodSlug: "alameda-park-st",
    price: 1150000,
    beds: 3,
    baths: 2,
    sqft: 1750,
    lotSqft: 4000,
    status: "active",
    propertyType: "house",
    description:
      "Charming Victorian on Alameda's beloved Park Street. Wraparound porch, bay windows, and original hardwood floors. Updated kitchen opens to a sunny breakfast nook. Walk to shops, restaurants, and the Alameda Theatre. Island living at its finest.",
    features: ["Victorian charm", "Wraparound porch", "Walk to shops", "Island living", "Updated kitchen"],
    yearBuilt: 1900,
    daysOnMarket: 11,
    pricePerSqft: 657,
    garage: 1,
    stories: 2,
    mlsNumber: "EB-40292150",
    listDate: "2026-02-20",
    images: [],
  },
  {
    id: "17",
    slug: "san-leandro-family-home",
    address: "890 Estudillo Ave",
    city: "San Leandro",
    neighborhood: "Estudillo Estates",
    neighborhoodSlug: "san-leandro",
    price: 985000,
    beds: 4,
    baths: 2.5,
    sqft: 2100,
    lotSqft: 6500,
    status: "active",
    propertyType: "house",
    description:
      "Spacious family home in San Leandro's prestigious Estudillo Estates. Formal living and dining rooms, updated kitchen with granite counters, and a large backyard with a built-in BBQ and fire pit. Great schools and an easy BART commute.",
    features: ["Large backyard", "BBQ & fire pit", "Great schools", "Near BART", "Estudillo Estates"],
    yearBuilt: 1955,
    daysOnMarket: 19,
    pricePerSqft: 469,
    garage: 2,
    stories: 1,
    mlsNumber: "EB-40291650",
    listDate: "2026-02-12",
    images: [],
  },
  {
    id: "18",
    slug: "emeryville-modern-townhouse",
    address: "5800 Hollis St #12",
    city: "Emeryville",
    neighborhood: "Emeryville",
    neighborhoodSlug: "emeryville",
    price: 825000,
    beds: 2,
    baths: 2.5,
    sqft: 1400,
    status: "active",
    propertyType: "townhouse",
    description:
      "Brand-new modern townhouse in Emeryville's thriving arts district. Open-concept living, private rooftop terrace with Bay views, attached garage with EV charger. Walk to Bay Street shops, Pixar campus nearby, and easy freeway access to SF or Berkeley.",
    features: ["Rooftop terrace", "EV charger", "Bay views", "New construction", "Walk to shops"],
    yearBuilt: 2025,
    daysOnMarket: 30,
    pricePerSqft: 589,
    garage: 1,
    stories: 3,
    hoa: 350,
    mlsNumber: "EB-40290988",
    listDate: "2026-02-01",
    images: [],
  },
  {
    id: "19",
    slug: "richmond-waterfront-home",
    address: "1200 Marina Way S",
    city: "Richmond",
    neighborhood: "Marina Bay",
    neighborhoodSlug: "richmond-marina",
    price: 795000,
    beds: 3,
    baths: 2,
    sqft: 1600,
    lotSqft: 3800,
    status: "active",
    propertyType: "house",
    description:
      "Waterfront gem in Richmond's Marina Bay with stunning views of Mt. Tamalpais and the San Francisco skyline. Open floor plan, vaulted ceilings, and a wraparound deck. Walk to the Bay Trail, ferry terminal, and Rosie the Riveter National Park.",
    features: ["Waterfront", "Mt. Tam views", "Bay Trail access", "Near ferry", "Wraparound deck"],
    yearBuilt: 2005,
    daysOnMarket: 21,
    pricePerSqft: 497,
    garage: 2,
    stories: 2,
    mlsNumber: "EB-40291444",
    listDate: "2026-02-10",
    images: [],
  },
  {
    id: "20",
    slug: "walnut-creek-luxury",
    address: "1475 N Broadway",
    city: "Walnut Creek",
    neighborhood: "Northgate",
    neighborhoodSlug: "walnut-creek",
    price: 1750000,
    beds: 4,
    baths: 3,
    sqft: 2900,
    lotSqft: 9000,
    status: "active",
    propertyType: "house",
    description:
      "Elegant Walnut Creek home in the desirable Northgate area. Soaring ceilings, gourmet kitchen with large island, primary suite with spa bath, and a resort-style backyard with pool and mature landscaping. Top-rated schools and downtown dining minutes away.",
    features: ["Pool", "Gourmet kitchen", "Spa bath", "Top schools", "Near downtown"],
    yearBuilt: 2002,
    daysOnMarket: 13,
    pricePerSqft: 603,
    garage: 3,
    stories: 2,
    mlsNumber: "EB-40292055",
    listDate: "2026-02-18",
    images: [],
  },

  // ─── SOLD PROPERTIES ──────────────────────────────────
  {
    id: "9",
    slug: "sold-craftsman-grand-lake",
    address: "3421 Grand Ave",
    city: "Oakland",
    neighborhood: "Grand Lake",
    neighborhoodSlug: "grand-lake",
    price: 1100000,
    beds: 3,
    baths: 2,
    sqft: 1650,
    lotSqft: 4200,
    status: "sold",
    propertyType: "house",
    description:
      "Beautiful Craftsman near the Grand Lake Theatre. Sold above asking with multiple offers in just 9 days. Original built-ins, remodeled kitchen, and a private backyard. Nasim's marketing strategy attracted 14 offers.",
    features: ["Multiple offers", "9 days on market", "Sold above asking"],
    yearBuilt: 1915,
    daysOnMarket: 9,
    pricePerSqft: 780,
    soldPrice: 1287000,
    soldDate: "2025-11",
    mlsNumber: "EB-40288912",
    images: [],
  },
  {
    id: "10",
    slug: "sold-modern-temescal",
    address: "4900 Clarke St",
    city: "Oakland",
    neighborhood: "Temescal",
    neighborhoodSlug: "temescal",
    price: 975000,
    beds: 3,
    baths: 2,
    sqft: 1550,
    lotSqft: 3600,
    status: "sold",
    propertyType: "house",
    description:
      "Modern renovated home in the heart of Temescal. Sold in 7 days with 11 offers. Open concept with designer finishes, ADU potential in the garage. Nasim's staging and photography made this listing stand out.",
    features: ["11 offers", "7 days on market", "ADU potential"],
    yearBuilt: 1948,
    daysOnMarket: 7,
    pricePerSqft: 737,
    soldPrice: 1142000,
    soldDate: "2025-09",
    mlsNumber: "EB-40287655",
    images: [],
  },
  {
    id: "21",
    slug: "sold-berkeley-bungalow",
    address: "2310 Ward St",
    city: "Berkeley",
    neighborhood: "South Berkeley",
    neighborhoodSlug: "south-berkeley",
    price: 895000,
    beds: 2,
    baths: 1,
    sqft: 1200,
    lotSqft: 4000,
    status: "sold",
    propertyType: "house",
    description:
      "Sweet Berkeley bungalow with ADU potential. Sold over asking in 5 days with 8 offers. Nasim's neighborhood expertise and targeted marketing to Berkeley buyers made the difference.",
    features: ["8 offers", "5 days on market", "Sold over asking", "ADU potential"],
    yearBuilt: 1924,
    daysOnMarket: 5,
    pricePerSqft: 871,
    soldPrice: 1045000,
    soldDate: "2026-01",
    mlsNumber: "EB-40289401",
    images: [],
  },
  {
    id: "22",
    slug: "sold-alameda-colonial",
    address: "1822 Central Ave",
    city: "Alameda",
    neighborhood: "East End",
    neighborhoodSlug: "alameda-east-end",
    price: 1050000,
    beds: 3,
    baths: 2,
    sqft: 1800,
    lotSqft: 5200,
    status: "sold",
    propertyType: "house",
    description:
      "Classic Alameda Colonial Revival. Sold at asking in 11 days. Nasim's open house strategy and social media campaign generated strong interest from island-loving buyers seeking community and character.",
    features: ["Sold at asking", "11 days on market", "Colonial Revival"],
    yearBuilt: 1910,
    daysOnMarket: 11,
    pricePerSqft: 583,
    soldPrice: 1050000,
    soldDate: "2025-12",
    mlsNumber: "EB-40289102",
    images: [],
  },
];

export const getActiveListings = (): Property[] => {
  return listings.filter((l) => l.status === "active" || l.status === "pending");
};

export const getSoldListings = (): Property[] => {
  return listings.filter((l) => l.status === "sold");
};

export const getFeaturedListings = (): Property[] => {
  return listings.filter((l) => l.status === "active").slice(0, 3);
};

export const getListingsByNeighborhood = (slug: string): Property[] => {
  return listings.filter((l) => l.neighborhoodSlug === slug);
};

export const getListingsByCity = (city: string): Property[] => {
  return listings.filter((l) => l.city === city);
};

export const getCities = (): string[] => {
  return [...new Set(listings.map((l) => l.city))].sort();
};
