import type { Neighborhood } from "@/types";

export const neighborhoods: Neighborhood[] = [
  {
    slug: "rockridge",
    name: "Rockridge",
    tagline: "Village charm meets urban sophistication",
    description:
      "Rockridge is one of Oakland's most beloved neighborhoods, known for its charming Craftsman homes, tree-lined streets, and the bustling College Avenue corridor. With easy BART access, world-class dining, and a tight-knit community feel, Rockridge offers the perfect blend of urban convenience and residential tranquility.",
    vibe: "Upscale village with indie shops, farm-to-table dining, and a strong sense of community",
    medianPrice: 1450000,
    walkScore: 88,
    transitScore: 72,
    schoolRating: 8,
    highlights: [
      { icon: "utensils", label: "Dining", value: "Farm-to-table restaurants" },
      { icon: "train", label: "Transit", value: "Rockridge BART station" },
      { icon: "trees", label: "Parks", value: "Hardy Park & trails" },
      { icon: "shopping-bag", label: "Shopping", value: "College Ave boutiques" },
    ],
    dining: ["Wood Tavern", "A Côté", "Zachary's Pizza", "Cactus Taqueria"],
    parks: ["Hardy Park", "Claremont Canyon Trail", "Frog Park"],
    culture: ["Diesel Bookstore", "College Ave galleries", "Rockridge Library"],
    transit: ["Rockridge BART", "AC Transit 51A", "Easy I-24/580 access"],
    heroColor: "from-emerald-900/80 to-teal-800/60",
    stockPhoto: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=75",
  },
  {
    slug: "temescal",
    name: "Temescal",
    tagline: "Oakland's creative and culinary heartbeat",
    description:
      "Temescal is Oakland's creative epicenter — a vibrant neighborhood where artists, chefs, and entrepreneurs thrive. Telegraph Avenue buzzes with eclectic restaurants, craft cocktail bars, and independent shops. The neighborhood's diversity, walkability, and artistic energy make it one of the most exciting places to live in the East Bay.",
    vibe: "Eclectic, artsy, and food-obsessed with a strong DIY culture",
    medianPrice: 1150000,
    walkScore: 92,
    transitScore: 68,
    schoolRating: 7,
    highlights: [
      { icon: "utensils", label: "Food Scene", value: "Top-rated restaurants" },
      { icon: "palette", label: "Arts", value: "Galleries & murals" },
      { icon: "shopping-bag", label: "Shopping", value: "Temescal Alley" },
      { icon: "music", label: "Nightlife", value: "Bars & live music" },
    ],
    dining: ["Burma Superstar", "Pizzaiolo", "Cholita Linda", "Homeroom"],
    parks: ["Temescal Regional Park", "Bushrod Park"],
    culture: ["Temescal Alley", "Oaklandish", "Art galleries on Telegraph"],
    transit: ["MacArthur BART", "AC Transit 6/NL", "Bike-friendly streets"],
    heroColor: "from-orange-900/80 to-amber-800/60",
    stockPhoto: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=75",
  },
  {
    slug: "montclair",
    name: "Montclair",
    tagline: "Hillside living with breathtaking views",
    description:
      "Nestled in the Oakland Hills, Montclair offers a serene, nature-filled lifestyle with stunning Bay views, excellent schools, and a charming village center. The neighborhood feels like a small town within a city — residents enjoy hiking trails right from their doorstep, a beloved independent bookstore, and a genuine sense of community.",
    vibe: "Peaceful hillside retreat with a close-knit village center",
    medianPrice: 1650000,
    walkScore: 62,
    transitScore: 42,
    schoolRating: 9,
    highlights: [
      { icon: "mountain", label: "Views", value: "Stunning Bay panoramas" },
      { icon: "graduation-cap", label: "Schools", value: "Top-rated schools" },
      { icon: "trees", label: "Nature", value: "Direct trail access" },
      { icon: "coffee", label: "Village", value: "Montclair Village shops" },
    ],
    dining: ["Montclair Egg Shop", "Sabrina's Café", "The Kebab Shop"],
    parks: ["Joaquin Miller Park", "Roberts Regional Park", "Shepherd Canyon"],
    culture: ["Montclair Village", "A Great Good Place for Books", "Montclair Art Gallery"],
    transit: ["AC Transit 33/NL", "Highway 13 access", "Park & Ride options"],
    heroColor: "from-green-900/80 to-emerald-800/60",
    stockPhoto: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=75",
  },
  {
    slug: "lake-merritt",
    name: "Lake Merritt",
    tagline: "Oakland's shimmering urban oasis",
    description:
      "Lake Merritt is the crown jewel of Oakland — a stunning saltwater lake surrounded by a 3.4-mile pedestrian path, gorgeous Craftsman apartments, and a lively cultural scene. From Saturday farmers markets to the historic Grand Lake Theatre, this neighborhood embodies the best of Oakland's urban vitality and natural beauty.",
    vibe: "Vibrant lakeside living with arts, dining, and community events",
    medianPrice: 850000,
    walkScore: 94,
    transitScore: 80,
    schoolRating: 6,
    highlights: [
      { icon: "waves", label: "Lakefront", value: "3.4-mile path" },
      { icon: "calendar", label: "Events", value: "Weekly farmers market" },
      { icon: "building", label: "Urban", value: "Walk to everything" },
      { icon: "bird", label: "Nature", value: "Wildlife sanctuary" },
    ],
    dining: ["Grand Lake Kitchen", "Boot & Shoe Service", "Lake Chalet", "Arizmendi Bakery"],
    parks: ["Lake Merritt Park", "Lakeside Park Garden", "Children's Fairyland"],
    culture: ["Grand Lake Theatre", "Oakland Museum of CA", "Lake Merritt Farmers Market"],
    transit: ["Lake Merritt BART", "19th St BART", "AC Transit multiple lines"],
    heroColor: "from-blue-900/80 to-cyan-800/60",
    stockPhoto: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=75",
  },
  {
    slug: "jack-london-square",
    name: "Jack London Square",
    tagline: "Oakland's waterfront playground",
    description:
      "Jack London Square is Oakland's premier waterfront district, blending industrial heritage with modern living. Named after the legendary author, this neighborhood features waterfront dining, a thriving food scene, and stunning Bay views. New condo developments and converted lofts attract young professionals and empty nesters alike.",
    vibe: "Modern waterfront living with restaurants, ferries, and Bay views",
    medianPrice: 750000,
    walkScore: 90,
    transitScore: 75,
    schoolRating: 5,
    highlights: [
      { icon: "anchor", label: "Waterfront", value: "Bay Trail access" },
      { icon: "ship", label: "Ferry", value: "SF Ferry service" },
      { icon: "utensils", label: "Dining", value: "Waterfront restaurants" },
      { icon: "building-2", label: "Lofts", value: "Modern condos & lofts" },
    ],
    dining: ["Belcampo", "Lungomare", "Plank", "Heinold's First & Last Chance"],
    parks: ["Jack London Square Waterfront", "Estuary Park", "Bay Trail"],
    culture: ["Jack London's cabin", "USS Potomac", "Sunday Farmers Market"],
    transit: ["12th St BART nearby", "SF Ferry", "Amtrak station", "I-880 access"],
    heroColor: "from-slate-900/80 to-blue-900/60",
    stockPhoto: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=75",
  },
  {
    slug: "piedmont-ave",
    name: "Piedmont Avenue",
    tagline: "Stately homes and neighborhood charm",
    description:
      "Piedmont Avenue is a tree-lined corridor of stunning early 20th century homes, independent shops, and beloved restaurants. Bordering the city of Piedmont, this neighborhood offers gracious living with a walkable main street, Mountain View Cemetery's park-like grounds, and a strong sense of historic character.",
    vibe: "Classic Oakland elegance with walkable shops and historic architecture",
    medianPrice: 1250000,
    walkScore: 85,
    transitScore: 60,
    schoolRating: 8,
    highlights: [
      { icon: "landmark", label: "Architecture", value: "Historic homes" },
      { icon: "shopping-bag", label: "Shopping", value: "Piedmont Ave shops" },
      { icon: "trees", label: "Green Space", value: "Mountain View Cemetery" },
      { icon: "film", label: "Entertainment", value: "Piedmont Theatre" },
    ],
    dining: ["Commis", "Shan Dong", "A16", "Piedmont Avenue restaurants"],
    parks: ["Mountain View Cemetery", "Piedmont Park", "Glen Echo Creek"],
    culture: ["Piedmont Theatre", "Chapel of the Chimes", "Fentons Creamery"],
    transit: ["AC Transit 33/12", "Near MacArthur BART", "Highway 13 access"],
    heroColor: "from-stone-900/80 to-amber-900/60",
    stockPhoto: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=75",
  },
  {
    slug: "fruitvale",
    name: "Fruitvale",
    tagline: "Oakland's vibrant cultural corridor",
    description:
      "Fruitvale is the cultural heart of Oakland's Latino community and one of the city's most dynamic neighborhoods. The Fruitvale Village transit hub, colorful murals, authentic taquerias, and community celebrations like Día de los Muertos make this neighborhood a rich, affordable, and exciting place to call home.",
    vibe: "Culturally rich, community-driven, and full of authentic flavor",
    medianPrice: 720000,
    walkScore: 86,
    transitScore: 70,
    schoolRating: 6,
    highlights: [
      { icon: "palette", label: "Culture", value: "Murals & festivals" },
      { icon: "utensils", label: "Food", value: "Authentic taquerias" },
      { icon: "train", label: "Transit", value: "Fruitvale BART" },
      { icon: "heart", label: "Community", value: "Strong local pride" },
    ],
    dining: ["Taqueria Sinaloa", "Mi Grullense", "La Finca", "Fruitvale Public Market"],
    parks: ["Josie de la Cruz Park", "Peralta Hacienda", "San Antonio Park"],
    culture: ["Fruitvale Village", "Día de los Muertos festival", "Unity Council"],
    transit: ["Fruitvale BART", "AC Transit multiple lines", "I-580 access"],
    heroColor: "from-red-900/80 to-orange-800/60",
    stockPhoto: "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&q=75",
  },
  {
    slug: "grand-lake",
    name: "Grand Lake",
    tagline: "Where Oakland's heart beats loudest",
    description:
      "Grand Lake sits at the intersection of Oakland's best offerings — steps from Lake Merritt, anchored by the iconic Grand Lake Theatre marquee, and home to the city's most popular farmers market. This walkable, diverse neighborhood offers beautiful Craftsman homes, great restaurants, and an unbeatable community vibe.",
    vibe: "Walkable, diverse, and buzzing with farmers market energy",
    medianPrice: 950000,
    walkScore: 93,
    transitScore: 74,
    schoolRating: 7,
    highlights: [
      { icon: "shopping-cart", label: "Market", value: "Grand Lake Farmers Market" },
      { icon: "film", label: "Landmark", value: "Grand Lake Theatre" },
      { icon: "map-pin", label: "Location", value: "Steps to Lake Merritt" },
      { icon: "home", label: "Homes", value: "Craftsman bungalows" },
    ],
    dining: ["Grand Lake Kitchen", "Boot & Shoe Service", "Sidebar", "Arizmendi"],
    parks: ["Lake Merritt", "Splash Pad Park", "Trestle Glen"],
    culture: ["Grand Lake Theatre", "Saturday Farmers Market", "Art Murmur"],
    transit: ["AC Transit NL/12", "Near Lake Merritt BART", "I-580 access"],
    heroColor: "from-violet-900/80 to-purple-800/60",
    stockPhoto: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=75",
  },
  {
    slug: "claremont",
    name: "Claremont",
    tagline: "Resort-style living in the Oakland Hills",
    description:
      "The Claremont neighborhood takes its name from the iconic Claremont Hotel and offers some of the most prestigious addresses in the East Bay. With grand Mediterranean and Tudor homes, sweeping Bay views, and proximity to both UC Berkeley and Rockridge, Claremont combines luxury with accessibility.",
    vibe: "Prestigious hillside living with panoramic views and resort amenities",
    medianPrice: 1800000,
    walkScore: 58,
    transitScore: 48,
    schoolRating: 9,
    highlights: [
      { icon: "hotel", label: "Landmark", value: "Claremont Hotel & Spa" },
      { icon: "mountain", label: "Views", value: "Panoramic Bay views" },
      { icon: "graduation-cap", label: "Schools", value: "Top-rated schools" },
      { icon: "sparkles", label: "Luxury", value: "Grand estates" },
    ],
    dining: ["Oliveto", "Limewood", "Corso"],
    parks: ["Claremont Canyon Reserve", "Indian Rock Park"],
    culture: ["Claremont Hotel & Spa", "UC Berkeley campus", "Elmwood district"],
    transit: ["Ashby BART nearby", "AC Transit 49/65", "Highway 13/24 access"],
    heroColor: "from-indigo-900/80 to-blue-800/60",
    stockPhoto: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=75",
  },
  {
    slug: "dimond",
    name: "Dimond",
    tagline: "Oakland's best-kept secret neighborhood",
    description:
      "Dimond is a hidden gem tucked along Dimond Canyon — a walkable, family-friendly neighborhood with a growing food scene, creek-side trails, and some of Oakland's best home values. The Dimond district on Fruitvale Avenue has blossomed with new restaurants, cafés, and community events.",
    vibe: "Family-friendly, up-and-coming, and connected to nature",
    medianPrice: 980000,
    walkScore: 78,
    transitScore: 55,
    schoolRating: 7,
    highlights: [
      { icon: "trees", label: "Nature", value: "Dimond Canyon trails" },
      { icon: "baby", label: "Families", value: "Family-friendly parks" },
      { icon: "trending-up", label: "Value", value: "Growing food scene" },
      { icon: "coffee", label: "Cafés", value: "Local coffee spots" },
    ],
    dining: ["La Farine Bakery", "Sequoia Diner", "Xolo Tacos", "District Oakland"],
    parks: ["Dimond Park", "Dimond Canyon Trail", "Leona Heights"],
    culture: ["Dimond Improvement Association", "Oaktoberfest", "Community garden"],
    transit: ["AC Transit 21/57", "Near Fruitvale BART", "I-580 access"],
    heroColor: "from-lime-900/80 to-green-800/60",
    stockPhoto: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=75",
  },
  {
    slug: "glenview",
    name: "Glenview",
    tagline: "A quiet haven with neighborhood soul",
    description:
      "Glenview is a peaceful residential neighborhood nestled between Park Boulevard and the Oakland Hills. Known for its mix of charming bungalows, mid-century homes, and tree-lined streets, Glenview offers a quiet, family-oriented lifestyle while remaining close to Lake Merritt and the Dimond district.",
    vibe: "Quiet, tree-lined streets with a strong neighborhood identity",
    medianPrice: 1050000,
    walkScore: 72,
    transitScore: 50,
    schoolRating: 7,
    highlights: [
      { icon: "home", label: "Homes", value: "Charming bungalows" },
      { icon: "trees", label: "Streets", value: "Tree-lined & quiet" },
      { icon: "map-pin", label: "Central", value: "Near Lake Merritt" },
      { icon: "store", label: "Local", value: "Park Blvd shops" },
    ],
    dining: ["Park Boulevard restaurants", "Glenview neighborhood cafés"],
    parks: ["Dimond Park nearby", "Glenview neighborhood paths"],
    culture: ["Park Boulevard corridor", "Glenview Elementary events"],
    transit: ["AC Transit 57", "Near Park Blvd", "I-580 access"],
    heroColor: "from-teal-900/80 to-cyan-800/60",
    stockPhoto: "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&q=75",
  },
  {
    slug: "adams-point",
    name: "Adams Point",
    tagline: "Lakeside living at its finest",
    description:
      "Adams Point wraps around the north shore of Lake Merritt, offering some of the most scenic urban living in the East Bay. With grand apartment buildings, lakefront jogging paths, and proximity to downtown Oakland, Adams Point is perfect for those who want nature, culture, and city life all within walking distance.",
    vibe: "Urban lakeside living with stunning views and walkable convenience",
    medianPrice: 680000,
    walkScore: 95,
    transitScore: 82,
    schoolRating: 6,
    highlights: [
      { icon: "waves", label: "Lakefront", value: "North shore of Lake Merritt" },
      { icon: "building", label: "Urban", value: "Walk to downtown" },
      { icon: "coffee", label: "Cafés", value: "Grand Ave corridor" },
      { icon: "dog", label: "Dog-Friendly", value: "Lakeside dog parks" },
    ],
    dining: ["Grand Avenue restaurants", "Lake Merritt cafés", "Ramen shops"],
    parks: ["Lake Merritt north shore", "Splash Pad Park", "Adams Point dog area"],
    culture: ["Grand Avenue shopping", "Fox Theater nearby", "First Fridays"],
    transit: ["19th St BART", "AC Transit NL", "Walk to downtown"],
    heroColor: "from-sky-900/80 to-blue-800/60",
    stockPhoto: "https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=800&q=75",
  },
];

export const getNeighborhood = (slug: string): Neighborhood | undefined => {
  return neighborhoods.find((n) => n.slug === slug);
};

export const getNeighborhoodNames = (): string[] => {
  return neighborhoods.map((n) => n.name);
};
