import type { Resource } from "@/types";

export const resources: Resource[] = [
  {
    id: "buyer-guide",
    title: "First-Time Buyer's Guide",
    description: "Everything you need to know about buying your first home in Oakland — from pre-approval to closing day.",
    category: "buyer",
    icon: "book-open",
    items: [
      "Get pre-approved for a mortgage before you start looking",
      "Understand your budget: factor in property taxes, insurance, and HOA fees",
      "Research Oakland neighborhoods that match your lifestyle and commute",
      "Attend open houses to understand market pricing and competition",
      "Work with a local agent (hi!) who knows the Oakland market intimately",
      "Be prepared to act fast — desirable homes sell in days, not weeks",
      "Get a home inspection — never skip this step, even in a competitive market",
      "Understand the difference between list price and market value in Oakland",
      "Explore first-time buyer programs and down payment assistance",
      "Plan for closing costs (typically 2-5% of purchase price)",
    ],
  },
  {
    id: "seller-guide",
    title: "Seller's Playbook",
    description: "Maximize your home's value with Nasim's proven strategy for selling in Oakland's competitive market.",
    category: "seller",
    icon: "megaphone",
    items: [
      "Price strategically — slightly below market to generate multiple offers",
      "Stage your home: professional staging increases sale price by 5-15%",
      "Invest in professional photography and video walkthrough",
      "Make cost-effective updates: fresh paint, landscaping, and decluttering go a long way",
      "Time your listing: spring and early fall see the highest buyer activity in Oakland",
      "Disclose everything upfront — it builds trust and avoids delays",
      "Create a compelling listing story that highlights your neighborhood",
      "Market beyond the MLS: social media, targeted outreach, and agent networks",
      "Be flexible with showings — the more accessible, the more offers",
      "Understand the offer review process and how to evaluate competing offers",
    ],
  },
  {
    id: "staging-tips",
    title: "Home Staging Tips",
    description: "Transform your space to make buyers fall in love the moment they walk through the door.",
    category: "seller",
    icon: "sparkles",
    items: [
      "Declutter ruthlessly — less is more when staging for sale",
      "Depersonalize: remove family photos and personal items",
      "Maximize natural light: open blinds, add mirrors, use light-colored linens",
      "Create a welcoming entryway: new doormat, potted plants, clean front door",
      "Stage the kitchen as a lifestyle space: fresh fruit, cookbooks, coffee station",
      "Make bedrooms feel like a hotel: crisp white bedding, minimal furniture",
      "Deep clean everything — especially kitchens, bathrooms, and windows",
      "Add fresh flowers or greenery to every room",
    ],
  },
  {
    id: "relocation-guide",
    title: "Oakland Relocation Guide",
    description: "Moving to Oakland? Here's your insider guide to finding your perfect neighborhood and settling in.",
    category: "general",
    icon: "map",
    items: [
      "Oakland has 50+ distinct neighborhoods — each with its own personality",
      "BART connects Oakland to SF, Berkeley, and the wider Bay Area",
      "Median home prices range from $680K (Adams Point) to $1.8M (Claremont)",
      "Oakland's food scene rivals SF — from Temescal taquerias to Rockridge fine dining",
      "The weather is warmer and sunnier than SF (less fog!)",
      "Lake Merritt is the jewel of the city — Oakland's Central Park",
      "Research school districts carefully — they vary significantly by neighborhood",
      "Oakland is one of the most diverse cities in America",
    ],
  },
];
